if (IOS)
    require_dep(ogg)
    require_dep(vorbis)
    require_dep(libsndfile)
else (IOS)
    require_dep(ogg)
    require_dep(vorbis)
    require_dep(flac)
    require_dep(opus)
    require_dep(libsndfile)
endif (IOS)

require_source_dep(liblouis)
