if (IOS)
    require_dep(ogg)
    require_dep(vorbis)
    require_dep(libsndfile)
else (IOS)
    require_dep(vorbis)
    require_dep(flac)
    require_dep(opus)
	if (APPLE)    
		require_dep(libsndfile SYSTEM)
	    require_dep(ogg SYSTEM)
	else()
		require_dep(libsndfile)
	    require_dep(ogg)
	endif()
endif (IOS)

require_source_dep(liblouis)

# mnxdom's dependencies. mnxdom itself is fetched by src/importexport/mnx,
# which points it at these prefixes instead of letting it fetch its own.
if (MUE_BUILD_IMPEXP_MNX_MODULE AND NOT MSS_USE_SYSTEM_MNXDOM)
    require_dep(nlohmann_json)
    require_dep(json_schema_validator)
endif()
